## Batalla Naval

In [2]:
import numpy as np
import random 
import colorama
from colorama import Fore
colorama.init()

In [3]:
board= np.zeros((10,10))
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [4]:
x =0
for x in range (4):
    board[3][x]=1
    

In [5]:
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
for x in range (3):
    board[x][6]= 1

In [7]:
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
def random_shots2():# cordenadas aleatorias
    x = 10
    
    shot=[0,0]
    shot_array=[shot]
    for i in range(100):
        coord_x  =random.randint(0,9)
        coord_y  =random.randint(0,9)
        shot_coords = [coord_x, coord_y]
        shot_array.append(shot_coords)
    
    return shot_array

In [9]:
random_shots2()

[[0, 0],
 [3, 0],
 [3, 7],
 [4, 7],
 [1, 9],
 [5, 4],
 [9, 0],
 [2, 0],
 [4, 7],
 [9, 8],
 [1, 2],
 [4, 7],
 [7, 7],
 [1, 0],
 [7, 4],
 [5, 3],
 [9, 6],
 [5, 7],
 [8, 0],
 [3, 5],
 [1, 5],
 [5, 3],
 [5, 8],
 [7, 8],
 [0, 8],
 [1, 5],
 [8, 0],
 [8, 7],
 [1, 5],
 [9, 3],
 [4, 4],
 [2, 8],
 [6, 9],
 [2, 5],
 [1, 1],
 [8, 5],
 [0, 7],
 [2, 6],
 [8, 3],
 [7, 6],
 [1, 2],
 [4, 7],
 [0, 8],
 [9, 8],
 [3, 2],
 [0, 5],
 [2, 8],
 [9, 0],
 [5, 1],
 [7, 4],
 [4, 4],
 [5, 1],
 [8, 0],
 [2, 2],
 [6, 0],
 [9, 4],
 [4, 9],
 [6, 3],
 [7, 7],
 [8, 6],
 [6, 8],
 [4, 5],
 [9, 4],
 [8, 4],
 [3, 0],
 [6, 4],
 [7, 2],
 [8, 2],
 [1, 6],
 [9, 3],
 [6, 6],
 [9, 5],
 [4, 7],
 [7, 2],
 [1, 9],
 [6, 6],
 [5, 1],
 [8, 6],
 [2, 2],
 [2, 6],
 [4, 0],
 [2, 4],
 [9, 9],
 [6, 2],
 [0, 0],
 [4, 9],
 [7, 6],
 [9, 4],
 [0, 0],
 [1, 9],
 [3, 9],
 [4, 9],
 [6, 7],
 [2, 9],
 [1, 9],
 [6, 6],
 [0, 4],
 [5, 9],
 [8, 7],
 [1, 0],
 [7, 4]]

In [10]:
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
shot =random_shots2()
x =[]
x = shot
x


[[0, 0],
 [6, 8],
 [2, 1],
 [5, 9],
 [9, 9],
 [6, 5],
 [9, 0],
 [8, 1],
 [9, 5],
 [1, 3],
 [2, 4],
 [9, 6],
 [3, 3],
 [5, 1],
 [2, 6],
 [1, 4],
 [0, 4],
 [8, 5],
 [7, 3],
 [0, 4],
 [8, 4],
 [4, 1],
 [4, 3],
 [7, 2],
 [1, 5],
 [2, 0],
 [6, 9],
 [6, 7],
 [9, 5],
 [7, 1],
 [9, 2],
 [2, 7],
 [8, 6],
 [4, 8],
 [3, 3],
 [7, 9],
 [0, 3],
 [3, 0],
 [5, 9],
 [6, 3],
 [8, 8],
 [4, 2],
 [4, 8],
 [5, 6],
 [9, 7],
 [9, 6],
 [9, 8],
 [0, 3],
 [3, 6],
 [3, 0],
 [5, 5],
 [3, 1],
 [7, 1],
 [8, 4],
 [1, 9],
 [3, 4],
 [8, 7],
 [8, 0],
 [1, 8],
 [1, 5],
 [6, 5],
 [2, 3],
 [9, 2],
 [4, 7],
 [4, 3],
 [8, 9],
 [7, 0],
 [4, 1],
 [8, 7],
 [2, 6],
 [0, 8],
 [4, 9],
 [1, 9],
 [1, 6],
 [1, 9],
 [4, 6],
 [0, 7],
 [7, 2],
 [3, 6],
 [6, 1],
 [3, 8],
 [4, 0],
 [1, 4],
 [1, 8],
 [7, 9],
 [7, 1],
 [6, 8],
 [5, 2],
 [0, 3],
 [2, 1],
 [3, 1],
 [8, 0],
 [3, 2],
 [7, 3],
 [0, 0],
 [5, 8],
 [9, 1],
 [3, 7],
 [6, 7],
 [5, 9],
 [0, 5]]

In [12]:
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
suma =0

In [14]:
def suma_componentes(matrix,suma):
    x = 0
    y = 0
    for x in range (10):
        for y in range (10):
            valor = matrix[x][y]
            suma+= valor
    return suma

In [15]:
add=0
suma_componentes(board,add)

7.0

In [16]:
suma = suma_componentes(board,add)
suma

7.0

In [17]:
adder = 0 
suma=0
shot_counter =0

In [18]:
suma_componentes(board,add)

7.0

Disparos y Tablero final

In [21]:
add=0
suma_matriz=0
shot_counter = 0
counter=0
counter_aux=0
counter_over100 =0

In [22]:
#hasta que la matriz esté vacia, es decir, en 0's

while(suma_componentes(board,add)>0):
    
    if(counter>=100):
        
        counter_over100=counter#no moverle a esto
        counter =0
        
        counter_aux=0
        while(counter_aux<100):     
            mag=[]
            mag=random_shots2()#recargamos
            shot_array= np.array(mag[counter_aux])
            x_coord = shot_array[0]
            y_coord = shot_array[1]
            board[x_coord][y_coord]
            counter_aux+=1
        
        
    else : 
         shot_array = np.asarray(shot[counter])#cargamos 1 disparo
    x_coord = shot_array[0]
    y_coord = shot_array[1]
    board[x_coord][y_coord]        
    print("Tiro en la posición",shot_array)
    print("valor en el tablero: ",board[x_coord][y_coord])
    if(board[x_coord][y_coord]==1):
        shot_counter+=1
        board[x_coord][y_coord]=0
        print("HIT!")
        new_x= x_coord
        new_y= y_coord
        #org_possition=board[x_coord][y_coord]
        if(new_x <9):
          while(new_x<9):
            new_x+=1
            if(board[new_x][y_coord]==1):
             shot_counter+=1
             board[new_x][y_coord]=0
             print("HIT!")
        elif(y_coord<9):
           while(new_y<9):
            new_y+=1
            if(board[x_coord][new_y]==1):
                shot_counter+=1
                board[x_coord][new_y]=0
                print("HIT!")          
        elif(new_x>0):
            while(new_x>0):
                new_x-=1
                if(board[new_x][y_coord]==1):
                 shot_counter+=1
                 board[new_x][y_coord]=0
                 print("HIT!")
        elif(new_y>0):
            while(new_y>0):
                new_y-=1
                if(board[x_coord][new_y]==1):
                 shot_counter+=1
                 board[x_coord][new_y]=0
                 print("HIT!")
    counter+=1  
    counter+=counter_over100
    suma_componentes(board,add)
    print ("Tiros acertados",shot_counter)# no moverle a esto
    print("Components de la matriz",suma_componentes(board,add))
    print("Tiros",counter)
    print("--------------")
   
                              
                
            

board 
  

Tiro en la posición [0 0]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 1
--------------
Tiro en la posición [6 8]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 2
--------------
Tiro en la posición [2 1]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 3
--------------
Tiro en la posición [5 9]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 4
--------------
Tiro en la posición [9 9]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 5
--------------
Tiro en la posición [6 5]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 6
--------------
Tiro en la posición [9 0]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 7
--------------
Tiro en la posición [8 1]
valor en el tablero:  0.0
Tiros acertados 0
Components de la matriz 7.0
Tiros 8
--------------
Tiro en la posición [9 5]
valor 

Tiro en la posición [4 1]
valor en el tablero:  0.0
Tiros acertados 4
Components de la matriz 3.0
Tiros 68
--------------
Tiro en la posición [8 7]
valor en el tablero:  0.0
Tiros acertados 4
Components de la matriz 3.0
Tiros 69
--------------
Tiro en la posición [2 6]
valor en el tablero:  0.0
Tiros acertados 4
Components de la matriz 3.0
Tiros 70
--------------
Tiro en la posición [0 8]
valor en el tablero:  0.0
Tiros acertados 4
Components de la matriz 3.0
Tiros 71
--------------
Tiro en la posición [4 9]
valor en el tablero:  0.0
Tiros acertados 4
Components de la matriz 3.0
Tiros 72
--------------
Tiro en la posición [1 9]
valor en el tablero:  0.0
Tiros acertados 4
Components de la matriz 3.0
Tiros 73
--------------
Tiro en la posición [1 6]
valor en el tablero:  1.0
HIT!
Tiros acertados 5
Components de la matriz 2.0
Tiros 74
--------------
Tiro en la posición [1 9]
valor en el tablero:  0.0
Tiros acertados 5
Components de la matriz 2.0
Tiros 75
--------------
Tiro en la posición

Components de la matriz 1.0
Tiros 134
--------------
Tiro en la posición [1 4]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 135
--------------
Tiro en la posición [7 9]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 136
--------------
Tiro en la posición [9 8]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 137
--------------
Tiro en la posición [7 2]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 138
--------------
Tiro en la posición [7 2]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 139
--------------
Tiro en la posición [6 2]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 140
--------------
Tiro en la posición [4 1]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 141
--------------
Tiro en la posición [3 6]
valor en el tablero:  0.0
Tiros acertados 6
Components de la

Tiro en la posición [5 2]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 201
--------------
Tiro en la posición [6 1]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 202
--------------
Tiro en la posición [4 2]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 203
--------------
Tiro en la posición [7 3]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 204
--------------
Tiro en la posición [4 8]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 205
--------------
Tiro en la posición [0 7]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 206
--------------
Tiro en la posición [0 1]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 207
--------------
Tiro en la posición [8 2]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 208
--------------
Tiro en la posic

Components de la matriz 1.0
Tiros 267
--------------
Tiro en la posición [4 7]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 268
--------------
Tiro en la posición [3 8]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 269
--------------
Tiro en la posición [3 5]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 270
--------------
Tiro en la posición [3 1]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 271
--------------
Tiro en la posición [3 1]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 272
--------------
Tiro en la posición [9 0]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 273
--------------
Tiro en la posición [7 2]
valor en el tablero:  0.0
Tiros acertados 6
Components de la matriz 1.0
Tiros 274
--------------
Tiro en la posición [9 3]
valor en el tablero:  0.0
Tiros acertados 6
Components de la

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
#hunde barcos con un 

i = 0
shot_counter = 0
shot = random_shots2()
for i in range (100):
   
    shot_array = np.asarray(shot[i])
    x_coord = shot_array[0]
    y_coord = shot_array[1]
    board[x_coord][y_coord]        
    print("Tiro en la posición",shot_array)
    
    print("valor en el tablero: ",board[x_coord][y_coord])
    if(board[x_coord][y_coord]==1):
        shot_counter+=1
        print("HIT!")
        board[x_coord][y_coord]=0
        new_x= x_coord
        new_y= y_coord
       
        if(new_x <9):
          while(new_x<9):
            new_x+=1
            if(board[new_x][y_coord]==1):
             shot_counter+=1
             board[new_x][y_coord]=0
             print("HIT!")
        elif(y_coord<10):
           while(new_y<9):
            new_y+=1
            if(board[x_coord][new_y]==1):
                shot_counter+=1
                [x_coord][new_y]=0
                print("HIT!")          
        elif(new_x>0):
            while(new_x>0):
                new_x-=1
                if(board[new_x][y_coord]==1):
                 shot_counter+=1
                 board[new_x][y_coord]=0
                 print("HIT!")
        elif(new_y>0):
            while(new_y>0):
                new_y-=1
                if(board[x_coord][new_y]==1):
                 shot_counter+=1
                 board[x_coord][new_y]=0
                 print("HIT!")    
    print(i)        
            
print ("Tiros acertados",shot_counter)
board 