In [5]:
import numpy as np
import random 
import colorama
from colorama import Fore
colorama.init()

In [6]:
board= np.zeros((10,10))
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
x =0
for x in range (4):
    board[3][x]=1
    

In [8]:
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [10]:
for x in range (3):
    board[x][6]= 1

In [11]:
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
def random_shots2():# cordenadas aleatorias
    x = 10
    
    shot=[0,0]
    shot_array=[shot]
    for i in range(100):
        coord_x  =random.randint(0,9)
        coord_y  =random.randint(0,9)
        shot_coords = [coord_x, coord_y]
        shot_array.append(shot_coords)
    
    return shot_array

In [ ]:
random_shots2()

In [ ]:
board

In [ ]:
shot =random_shots2()
x =[]
x = shot
x


In [ ]:
board

In [ ]:
suma =0

In [ ]:
def suma_componentes(matrix,suma):
    x = 0
    y = 0
    for x in range (10):
        for y in range (10):
            valor = matrix[x][y]
            suma+= valor
    return suma

In [ ]:
add=0
suma_componentes(board,add)

In [ ]:
suma = suma_componentes(board,add)
suma

In [ ]:
adder = 0 
suma=0
shot_counter =0

In [ ]:
suma_componentes(board,add)

In [ ]:
add=0
suma_matriz=0
shot_counter = 0
counter=0
counter_aux=0

In [ ]:
#hasta que la matriz esté vacia, es decir, en 0's

while(suma_componentes(board,add)>0):
    
    if(counter>=100):
        
        counter_over100=counter#no moverle a esto
        counter =0
        
        counter_aux=0
        while(counter_aux<100):     
            mag=[]
            mag=random_shots2()#recargamos
            shot_array= np.array(mag[counter_aux])
            x_coord = shot_array[0]
            y_coord = shot_array[1]
            board[x_coord][y_coord]
            counter_aux+=1
        
        
    else : 
         shot_array = np.asarray(shot[counter])#cargamos 1 disparo
    x_coord = shot_array[0]
    y_coord = shot_array[1]
    board[x_coord][y_coord]        
    print("Tiro en la posición",shot_array)
    print("valor en el tablero: ",board[x_coord][y_coord])
    if(board[x_coord][y_coord]==1):
        shot_counter+=1
        board[x_coord][y_coord]=0
        print("HIT!")
        new_x= x_coord
        new_y= y_coord
        #org_possition=board[x_coord][y_coord]
        if(new_x <9):
          while(new_x<9):
            new_x+=1
            if(board[new_x][y_coord]==1):
             shot_counter+=1
             board[new_x][y_coord]=0
             print("HIT!")
        elif(y_coord<9):
           while(new_y<9):
            new_y+=1
            if(board[x_coord][new_y]==1):
                shot_counter+=1
                board[x_coord][new_y]=0
                print("HIT!")          
        elif(new_x>0):
            while(new_x>0):
                new_x-=1
                if(board[new_x][y_coord]==1):
                 shot_counter+=1
                 board[new_x][y_coord]=0
                 print("HIT!")
        elif(new_y>0):
            while(new_y>0):
                new_y-=1
                if(board[x_coord][new_y]==1):
                 shot_counter+=1
                 board[x_coord][new_y]=0
                 print("HIT!")
    counter+=1  
    counter+=counter_over100
    suma_componentes(board,add)
    print ("Tiros acertados",shot_counter)# no moverle a esto
    print("Components de la matriz",suma_componentes(board,add))
    print("Tiros",counter)
    print("--------------")
   
                              
                
            

board 
  

In [ ]:
#hunde barcos con un 

i = 0
shot_counter = 0
shot = random_shots2()
for i in range (100):
   
    shot_array = np.asarray(shot[i])
    x_coord = shot_array[0]
    y_coord = shot_array[1]
    board[x_coord][y_coord]        
    print("Tiro en la posición",shot_array)
    
    print("valor en el tablero: ",board[x_coord][y_coord])
    if(board[x_coord][y_coord]==1):
        shot_counter+=1
        print("HIT!")
        board[x_coord][y_coord]=0
        new_x= x_coord
        new_y= y_coord
       
        if(new_x <9):
          while(new_x<9):
            new_x+=1
            if(board[new_x][y_coord]==1):
             shot_counter+=1
             board[new_x][y_coord]=0
             print("HIT!")
        elif(y_coord<10):
           while(new_y<9):
            new_y+=1
            if(board[x_coord][new_y]==1):
                shot_counter+=1
                [x_coord][new_y]=0
                print("HIT!")          
        elif(new_x>0):
            while(new_x>0):
                new_x-=1
                if(board[new_x][y_coord]==1):
                 shot_counter+=1
                 board[new_x][y_coord]=0
                 print("HIT!")
        elif(new_y>0):
            while(new_y>0):
                new_y-=1
                if(board[x_coord][new_y]==1):
                 shot_counter+=1
                 board[x_coord][new_y]=0
                 print("HIT!")    
    print(i)        
            
print ("Tiros acertados",shot_counter)
board 